### PR TITLE
Adds support for --moduleResolution node

### PR DESCRIPTION
**Pull request by bouzuya**
before:

```
// ./add/index.js 
import { add } from "./add";
// ↓
import { add } from "./add.js"; // not found
```

after:

```
// ./add/index.js
import { add } from "./add";
// ↓
import { add } from "./add/index.js";
```

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Thanks for the PR @bouzuya!

I believe ES Modules do not support loading by folder name, which is what you appear to be trying to work around with this PR?  I'm hesitant to extend the transformer to support this convention because I believe the long term plan is to deprecate it.  The reason this transformer exists is to make it so it is *possible* to write TS that works in ts-node + browser + deno + NodeJS ESM.  I would prefer not to increase this project's complexity by adding features that aren't critically necessary to achieve that goal.  In this case, the author could simply update their imports to `import { add } from './add/index'` and they should now work in all environments, thus no need for a transformer.

That being said, I *do* encourage you to fork this repository and publish your own version of the transformer that does additional tasks that you find valuable (such as this).  The source code is licensed as public domain so you can do whatever you want with it, you don't even need to give attribution.  😄

Side note: I do like the diff thing you did with the tests, though I don't think it works on Windows (only platforms with a `diff` command I believe?).

**Comment by bouzuya** [comment]
Thenk you for your comment. I will create a new transformer. I think your policy is correct. However, `import {add} from './add';` does not cause a compilation error when moduleResolution is node. And don't forget that your transformer then outputs a broken NodeJS ESM.

**Comment by MicahZoltu** [comment]
> `import {add} from './add';` does not cause a compilation error when moduleResolution is node. And don't forget that your transformer then outputs a broken NodeJS ESM.

@bouzuya Hmm, are you sure about this?  I thought NodeJS in ESM mode wouldn't do node-style module resolution like that at runtime?  That is, if you have the following in an `.mjs` file it will be a runtime failure (assuming `./add` is a folder with an `index.mjs` file in it):
```js
import { add } from './add'
```

**Comment by bouzuya** [comment]
Node.js ESM behavior tests.

```bash
#!/bin/bash

if [ -z "$1" ]; then echo 'Usage: ./node-esm-test.sh <0|1|2|3|4|5>'; exit 1; fi

echo 'node --version'
node --version # v14.2.0

case $1 in
  0)
    echo "case 0: Node.js CJS resolves './add' -> './add/index.js'"
    mkdir node-esm-test
    cd node-esm-test
    mkdir add
    echo 'exports.add = function(a, b) { return a + b; };' > add/index.js
    echo 'const { add } = require("./add"); console.log(add(1, 2) === 3 ? "OK" : "NG");' > mod.js
    # OK
    node mod.js || true
    cd ..
    rm -rf node-esm-test
    ;;

  1)
    echo "case 1: Node.js ESM resolves './add/index.js' -> './add/index.js'"
    mkdir node-esm-test
    cd node-esm-test
    mkdir add
    echo 'export function add(a, b) { return a + b; }' > add/index.js
    echo 'import { add } from "./add/index.js"; console.log(add(1, 2) === 3 ? "OK" : "NG");' > mod.js
    echo '{"type":"module"}' > package.json
    # OK
    node mod.js || true
    cd ..
    rm -rf node-esm-test
    ;;

  2)
    echo "case 2: Node.js ESM doesn't resolve './add/index' -> './add/index.js'"
    mkdir node-esm-test
    cd node-esm-test
    mkdir add
    echo 'export function add(a, b) { return a + b; }' > add/index.js
    echo 'import { add } from "./add/index"; console.log(add(1, 2) === 3 ? "OK" : "NG");' > mod.js
    echo '{"type":"module"}' > package.json
    # cannot find module ... Did you mean to import ../add/index.js?
    node mod.js || true
    cd ..
    rm -rf node-esm-test
    ;;

  3)
    echo "case 3: Node.js ESM doesn't resolve './add' -> './add/index.js'"
    mkdir node-esm-test
    cd node-esm-test
    mkdir add
    echo 'export function add(a, b) { return a + b; }' > add/index.js
    echo 'import { add } from "./add"; console.log(add(1, 2) === 3 ? "OK" : "NG");' > mod.js
    echo '{"type":"module"}' > package.json
    # cannot find module ... Did you mean to import ../add/index.js?
    node mod.js || true
    cd ..
    rm -rf node-esm-test
    ;;

  4)
    echo "case 4: Node.js ESM doesn't resolve './add.js' -> './add/index.js'"
    mkdir node-esm-test
    cd node-esm-test
    mkdir add
    echo 'export function add(a, b) { return a + b; }' > add/index.js
    echo 'import { add } from "./add.js"; console.log(add(1, 2) === 3 ? "OK" : "NG");' > mod.js
    echo '{"type":"module"}' > package.json
    # cannot find module
    node mod.js || true
    cd ..
    rm -rf node-esm-test
    ;;

  5)
    echo "case 5: Node.js ESM doesn't resolve './add' -> './add/index.mjs'"
    mkdir node-esm-test
    cd node-esm-test
    mkdir add
    echo 'export function add(a, b) { return a + b; }' > add/index.mjs
    echo 'import { add } from "./add"; console.log(add(1, 2) === 3 ? "OK" : "NG");' > mod.mjs
    # cannot find module
    node mod.mjs || true
    cd ..
    rm -rf node-esm-test
    ;;

esac
```

**Comment by MicahZoltu** [comment]
Have you reported this as a bug to TypeScript?  It seems incorrect that they would support that aspect of `moduleResolution: node` when emitting `es2015` modules, seeing as how there is no runtime that will actually allow that.

**Comment by bouzuya** [comment]
I haven't reported. However, it may not be easy to change due to backward compatibility issues. I think the problem is that TypeScript ESM doesn't work properly at any runtime. But that's why I was thinking of temporarily working around with this transformer. 

(As you know, I'm not good at English, so it's hard to convey my thoughts.)

**Comment by MicahZoltu** [comment]
I filed an issue over on the TypeScript GitHub repo to see what their thoughts are on the matter: https://github.com/microsoft/TypeScript/issues/38729

**Pull request closed without merging**
